CREATE DATABASE  IF NOT EXISTS `assign_3` ;
USE `assign_3`;

-- Host: localhost    Database: assign_3
-- ------------------------------------------------------
-- Server version	8.3.0
 
 
--
-- Table structure for table `articles`
--
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS articles;
CREATE TABLE articles (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(500) NOT NULL DEFAULT 'Title',
    BODY TEXT NOT NULL,
    TAGS VARCHAR(200) DEFAULT NULL,
    USER_ID INT NOT NULL,
    WEBPAGE_ID INT NOT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY USER_FK_idx (USER_ID),
    KEY WEBPAGE_FK_idx (WEBPAGE_ID),
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
        REFERENCES users (ID),
    CONSTRAINT WEBPAGE_FK FOREIGN KEY (WEBPAGE_ID)
        REFERENCES webpages (ID)
)  ENGINE=INNODB AUTO_INCREMENT=12 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;

--
-- Table structure for table `roles`
--

DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
    ID INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) DEFAULT NULL,
    `DESCRIPTION` VARCHAR(1000) DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY NAME_UNIQUE (`NAME`)
)  ENGINE=INNODB AUTO_INCREMENT=6 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    ID INT NOT NULL AUTO_INCREMENT,
    FNAME VARCHAR(45) NOT NULL,
    LNAME VARCHAR(45) NOT NULL,
    USERNAME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    PHONE VARCHAR(45) NOT NULL,
    ROLE_ID INT NOT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY USERNAME (USERNAME),
    UNIQUE KEY EMAIL (EMAIL),
    UNIQUE KEY USERNAME_UNIQUE (USERNAME),
    UNIQUE KEY EMAIL_UNIQUE (EMAIL),
    UNIQUE KEY ID_UNIQUE (ID),
    KEY ROLE_FK_idx (ROLE_ID),
    CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID)
        REFERENCES roles (ID)
)  ENGINE=INNODB AUTO_INCREMENT=13 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;

--
-- Table structure for table `webpages`
--

DROP TABLE IF EXISTS webpages;
CREATE TABLE webpages (
    ID INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NOT NULL COMMENT 'name of webpage/directory',
    ARTICLE_CO INT(10) UNSIGNED ZEROFILL DEFAULT NULL COMMENT 'Number of articles in this page',
    MOD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Creation/Update Date',
    PRIMARY KEY (ID),
    UNIQUE KEY Name_UNIQUE (`NAME`),
    UNIQUE KEY ID_UNIQUE (ID)
)  ENGINE=INNODB AUTO_INCREMENT=6 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;

SET FOREIGN_KEY_CHECKS = 1;

